[build]
  command = "npm run build || exit 0"
  publish = ".next"

[build.environment]
  NEXT_TELEMETRY_DISABLED = "1"
  NEXT_LINT_IGNORE_ERRORS = "1"
  NODE_ENV = "production"
  SKIP_PREFLIGHT_CHECK = "true"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 